import React, { createContext, useState, useEffect } from "react";

// Define translations langsung di sini (ga perlu import JSON)
const translations = {
  id: {
    nav: {
      home: "Beranda",
      events: "Kegiatan",
      services: "Layanan",
      articles: "Artikel",
      gallery: "Galeri",
      about: "Tentang",
      pos: "POS",
    },
    services: {
      aromatherapy_workshop: "Workshop Aromaterapi",
      perfume_workshop: "Workshop Parfum",
      custom: "Buat Parfum & Aromaterapi",
      lab_tools: "Alat Laboratorium",
      ingredients: "Bahan Parfum & Aromaterapi",
      products: "Produk Parfum & Aromaterapi",
    },
    common: {
      language: "Bahasa:",
      loading: "Memuat...",
      search: "Cari",
      clear_search: "Hapus pencarian",
      no_data: "Tidak ada data tersedia",
      send: "Kirim",
      view_more: "Lihat Selengkapnya",
      back: "Kembali",
      share: "Bagikan",
      read_more: "Baca Selengkapnya",
      date: "Tanggal",
      time: "Waktu",
      location: "Lokasi",
      category: "Kategori",
      price: "Harga",
      stock: "Stok",
      description: "Deskripsi",
      related: "Terkait",
      author: "Penulis",
      published: "Dipublikasikan",
      add_to_cart: "Tambah ke Keranjang",
      buy_now: "Beli Sekarang",
      contact_us: "Hubungi Kami",
      register: "Daftar",
      available: "Tersedia",
      sold_out: "Habis",
      in_stock: "Stok Tersedia",
      out_of_stock: "Stok Habis",
    },
    homepage: {
      our_services: "Layanan Kami",
      our_services_desc: "Dari workshop hingga pembuatan parfum personal, kami siap melayani.",
      latest_events: "Kegiatan Terbaru",
      featured_products: "Produk Unggulan",
      latest_articles: "Artikel Terbaru",
      event_gallery: "Galeri Kegiatan",
      service_aromatherapy_desc: "Pelajari seni meracik parfum dengan panduan ahli.",
      service_perfume_desc: "Belajar meracik parfum personal dengan mudah.",
      service_custom_desc: "Kreasikan aroma unikmu dengan panduan kami.",
      service_products_desc: "Temukan koleksi parfum unik kami.",
      service_lab_desc: "Peralatan lab skala mikro standar industri.",
      service_ingredients_desc: "Jelajahi bahan baku pilihan kami.",
    },
    events: {
      title: "Kegiatan & Event",
      subtitle: "Ikuti berbagai kegiatan menarik yang kami selenggarakan.",
      search_placeholder: "Cari event berdasarkan nama, lokasi, atau kategori...",
      showing: "Menampilkan",
      of: "dari",
      event: "event",
      no_results: "Tidak ada event yang cocok dengan pencarian",
      loading: "Loading Events...",
      no_events: "Belum ada kegiatan yang tersedia saat ini.",
      event_details: "Detail Kegiatan",
      start_date: "Tanggal Mulai",
      end_date: "Tanggal Selesai",
      quota: "Kuota",
      participants: "Peserta",
      registration_open: "Pendaftaran Dibuka",
      registration_closed: "Pendaftaran Ditutup",
      event_info: "Informasi Kegiatan",
      related_events: "Kegiatan Terkait",
    },
    articles: {
      title: "Artikel Terbaru",
      subtitle: "Jelajahi wawasan, tips, dan cerita dari dunia parfum dan aromaterapi.",
      search_placeholder: "Cari artikel berdasarkan judul, kategori, atau konten...",
      showing: "Menampilkan",
      of: "dari",
      article: "artikel",
      no_results: "Tidak ada artikel yang cocok dengan pencarian",
      loading: "Loading Articles...",
      no_articles: "Belum ada artikel yang dipublikasikan.",
      article_detail: "Detail Artikel",
      related_articles: "Artikel Terkait",
      share_article: "Bagikan Artikel",
    },
    products: {
      title: "Produk Kami",
      subtitle: "Temukan koleksi parfum dan aromaterapi berkualitas.",
      search_placeholder: "Cari produk...",
      showing: "Menampilkan",
      of: "dari",
      product: "produk",
      no_results: "Tidak ada produk yang cocok dengan pencarian",
      loading: "Loading Products...",
      no_products: "Belum ada produk tersedia.",
      product_detail: "Detail Produk",
      related_products: "Produk Terkait",
      specifications: "Spesifikasi",
      how_to_use: "Cara Penggunaan",
      ingredients: "Bahan",
      benefits: "Manfaat",
    },
    gallery: {
      title: "Galeri Kegiatan",
      subtitle: "Momen-momen berharga dari setiap workshop dan event kami.",
      loading: "Loading Gallery...",
      no_images: "Belum ada gambar di galeri saat ini.",
    },
    about: {
      title: "About Us",
      contact_us: "Hubungi Kami",
      send_message: "Kirim Pesan",
      address: "Alamat",
      phone: "Telepon",
      email: "Email",
      instagram: "Instagram",
      visit_instagram: "Kunjungi Instagram kami",
      form_name: "Nama Lengkap",
      form_name_placeholder: "Masukkan nama Anda",
      form_email: "Email",
      form_email_placeholder: "email@example.com",
      form_phone: "Nomor Telepon",
      form_phone_placeholder: "+62 xxx xxxx xxxx",
      form_message: "Pesan",
      form_message_placeholder: "Tulis pesan Anda di sini...",
      form_submit: "Kirim Pesan",
      loading: "Loading...",
      no_info: "Informasi tidak tersedia.",
    },
  },
  en: {
    nav: {
      home: "Home",
      events: "Events",
      services: "Services",
      articles: "Articles",
      gallery: "Gallery",
      about: "About",
      pos: "POS",
    },
    services: {
      aromatherapy_workshop: "Aromatherapy Workshop",
      perfume_workshop: "Perfume Workshop",
      custom: "Custom Perfume & Aromatherapy",
      lab_tools: "Laboratory Equipment",
      ingredients: "Perfume & Aromatherapy Ingredients",
      products: "Perfume & Aromatherapy Products",
    },
    common: {
      language: "Language:",
      loading: "Loading...",
      search: "Search",
      clear_search: "Clear search",
      no_data: "No data available",
      send: "Send",
      view_more: "View More",
      back: "Back",
      share: "Share",
      read_more: "Read More",
      date: "Date",
      time: "Time",
      location: "Location",
      category: "Category",
      price: "Price",
      stock: "Stock",
      description: "Description",
      related: "Related",
      author: "Author",
      published: "Published",
      add_to_cart: "Add to Cart",
      buy_now: "Buy Now",
      contact_us: "Contact Us",
      register: "Register",
      available: "Available",
      sold_out: "Sold Out",
      in_stock: "In Stock",
      out_of_stock: "Out of Stock",
    },
    homepage: {
      our_services: "Our Services",
      our_services_desc: "From workshops to custom perfume creation, we're here to serve.",
      latest_events: "Latest Events",
      featured_products: "Featured Products",
      latest_articles: "Latest Articles",
      event_gallery: "Event Gallery",
      service_aromatherapy_desc: "Learn the art of aromatherapy with expert guidance.",
      service_perfume_desc: "Learn to create your personal perfume easily.",
      service_custom_desc: "Create your unique aroma with our guidance.",
      service_products_desc: "Discover our unique perfume collection.",
      service_lab_desc: "Industry-standard micro-scale laboratory equipment.",
      service_ingredients_desc: "Explore our premium ingredients.",
    },
    events: {
      title: "Events & Activities",
      subtitle: "Join our exciting events and activities.",
      search_placeholder: "Search events by name, location, or category...",
      showing: "Showing",
      of: "of",
      event: "events",
      no_results: "No events match your search for",
      loading: "Loading Events...",
      no_events: "No events available at the moment.",
      event_details: "Event Details",
      start_date: "Start Date",
      end_date: "End Date",
      quota: "Quota",
      participants: "Participants",
      registration_open: "Registration Open",
      registration_closed: "Registration Closed",
      event_info: "Event Information",
      related_events: "Related Events",
    },
    articles: {
      title: "Latest Articles",
      subtitle: "Explore insights, tips, and stories from the world of perfume and aromatherapy.",
      search_placeholder: "Search articles by title, category, or content...",
      showing: "Showing",
      of: "of",
      article: "articles",
      no_results: "No articles match your search for",
      loading: "Loading Articles...",
      no_articles: "No articles published yet.",
      article_detail: "Article Details",
      related_articles: "Related Articles",
      share_article: "Share Article",
    },
    products: {
      title: "Our Products",
      subtitle: "Discover our quality perfume and aromatherapy collection.",
      search_placeholder: "Search products...",
      showing: "Showing",
      of: "of",
      product: "products",
      no_results: "No products match your search for",
      loading: "Loading Products...",
      no_products: "No products available yet.",
      product_detail: "Product Details",
      related_products: "Related Products",
      specifications: "Specifications",
      how_to_use: "How to Use",
      ingredients: "Ingredients",
      benefits: "Benefits",
    },
    gallery: {
      title: "Event Gallery",
      subtitle: "Precious moments from every workshop and event.",
      loading: "Loading Gallery...",
      no_images: "No images in the gallery yet.",
    },
    about: {
      title: "About Us",
      contact_us: "Contact Us",
      send_message: "Send Message",
      address: "Address",
      phone: "Phone",
      email: "Email",
      instagram: "Instagram",
      visit_instagram: "Visit our Instagram",
      form_name: "Full Name",
      form_name_placeholder: "Enter your name",
      form_email: "Email",
      form_email_placeholder: "email@example.com",
      form_phone: "Phone Number",
      form_phone_placeholder: "+62 xxx xxxx xxxx",
      form_message: "Message",
      form_message_placeholder: "Write your message here...",
      form_submit: "Send Message",
      loading: "Loading...",
      no_info: "Information not available.",
    },
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // Ambil bahasa dari localStorage atau default ke 'id'
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "id";
  });

  // Simpan ke localStorage setiap kali bahasa berubah
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  // Function untuk translate
  const t = (key) => {
    const keys = key.split(".");
    let result = translations[language];

    for (const k of keys) {
      result = result[k];
      if (!result) return key; // Return key asli kalau ga ketemu
    }

    return result;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return <LanguageContext.Provider value={{ language, changeLanguage, t }}>{children}</LanguageContext.Provider>;
};

// Export context untuk digunakan di file lain
export { LanguageContext };
